language: python
matrix:
  include:
    - python: 3.6
      env:
      - TOXENV=py36
    - python: 3.7
      env:
      - TOXENV=py37
    - python: pypy
      env:
      - TOXENV=pypy
    - python: pypy3
      env:
      - TOXENV=pypy3
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
deploy:
  provider: pypi
  user: sergio-bershadsky
  distributions: sdist bdist_wheel
  on:
    condition: $TOXENV == py27
    tags: true
    all_branches: true
    repo: sergio-bershadsky/todo.report
